
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/container/Footer'
import Navbar from '@/components/Navbar'

import  NavbarMobile  from '@/components/navbarMobile/NavbarMobile'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-Poppins ${inter.className}`}>
        <Navbar/>  
        <NavbarMobile />

        {children}
        <Footer/>  
      </body>
    </html>
  )
}
