
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/container/Footer'
import Navbar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-Poppins ${inter.className}`}>
        <main className='container myborder-ct bg-gray-200 min-w-[350px]'>
          <div className='flex flex-col h-screen '>
            <Navbar/>  
            <div className='flex-1 overflow-y-scroll scrollbar-thin scrollbar-track-white scrollbar-thumb-slate-200'>
              {children}
    
                <Footer/> 
            </div>
      
          </div>
        </main>
      </body>
    </html>
  )
}
